### ISSUE TITLE
include a 2dii custom ggplot theme

### ISSUE THREAD

**Issue by cjyetman** [2DegreesInvesting/r2dii.ggplot#19]
Include a 2dii custom ggplot theme that could combine official 2dii color palette/s, official 2dii font specs, and other data viz guidances from @MonikaFu 

Such a custom ggplot theme could then be applied to any custom ggplot that a 2dii user may be creating.

see this package for some cool, complex examples: https://github.com/hrbrmstr/hrbrthemes

I believe @vintented may have made something like this before, or was that an Rmarkdown theme?

**Comment by MonikaFu** [comment]
great idea!
