### ISSUE TITLE
Tag this repo as deprecated and close all open PRs

### ISSUE THREAD

**Issue by jdhoffa** [2DegreesInvesting/r2dii.ggplot#2]
this repo is deprecated and superseded by r2dii.plot as far as I know

_Originally posted by @MonikaFu in https://github.com/RMI-PACTA/r2dii.ggplot/issues/1#issuecomment-1660137365_

**Comment by jdhoffa** [comment]
Basically just explain that it's deprecated in the README, and reference the replacement package:
https://github.com/RMI-PACTA/PACTA_analysis/pull/644/files

also I think you can archive the package in "GH > Settings"

**Comment by MonikaFu** [comment]
It already is part of the README
<img width="890" alt="image" src="https://github.com/RMI-PACTA/r2dii.ggplot/assets/26434113/f53477ea-433c-4857-9a75-172b36fb56a4">

**Comment by jdhoffa** [comment]
Oh what the heck, how did I not see this? 

Closing this issue.
